import {
  FileJson,
  Code,
  Link,
  Key,
  Hash,
  Palette,
  TestTube,
  FileCode,
  Sparkles,
  Terminal,
  FileText,
  BookOpen,
  Clock,
  Container,
  Search,
  QrCode,
  Lock,
  FileDiff,
  Database,
  Type,
  Image,
  Calendar,
  AlignLeft,
  FileCode2,
  Layers,
  BarChart3,
  Upload,
  Network,
} from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  href: string;
  icon: typeof FileJson;
  category: string;
}

export const tools: Tool[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate and beautify JSON data",
    href: "/tools/json-formatter",
    icon: FileJson,
    category: "Formatters",
  },
  {
    id: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings",
    href: "/tools/base64",
    icon: Code,
    category: "Encoders",
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URL strings",
    href: "/tools/url-encoder",
    icon: Link,
    category: "Encoders",
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug regular expressions",
    href: "/tools/regex-tester",
    icon: TestTube,
    category: "Testers",
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens",
    href: "/tools/jwt-decoder",
    icon: Key,
    category: "Security",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    href: "/tools/hash-generator",
    icon: Hash,
    category: "Security",
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUID v1 and v4 identifiers",
    href: "/tools/uuid-generator",
    icon: Sparkles,
    category: "Generators",
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between formats",
    href: "/tools/color-picker",
    icon: Palette,
    category: "Generators",
  },
  {
    id: "api-tester",
    name: "API Tester",
    description: "Test REST APIs with custom requests",
    href: "/tools/api-tester",
    icon: FileCode,
    category: "Testers",
  },
  {
    id: "shell-command-builder",
    name: "Shell Command Builder",
    description: "Visual builder for complex shell commands",
    href: "/tools/shell-command-builder",
    icon: Terminal,
    category: "Shell Tools",
  },
  {
    id: "shell-formatter",
    name: "Shell Script Formatter",
    description: "Format and validate bash scripts",
    href: "/tools/shell-formatter",
    icon: FileText,
    category: "Shell Tools",
  },
  {
    id: "command-cheatsheet",
    name: "Command Cheatsheet",
    description: "Searchable database of common commands",
    href: "/tools/command-cheatsheet",
    icon: BookOpen,
    category: "Shell Tools",
  },
  {
    id: "cron-builder",
    name: "Cron Expression Builder",
    description: "Visual builder for cron expressions",
    href: "/tools/cron-builder",
    icon: Clock,
    category: "Shell Tools",
  },
  {
    id: "docker-builder",
    name: "Docker Command Builder",
    description: "Build Docker commands visually",
    href: "/tools/docker-builder",
    icon: Container,
    category: "Shell Tools",
  },
  {
    id: "regex-to-grep",
    name: "Regex to Grep Converter",
    description: "Convert regex patterns to grep commands",
    href: "/tools/regex-to-grep",
    icon: Search,
    category: "Shell Tools",
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords with custom options",
    href: "/tools/password-generator",
    icon: Lock,
    category: "Security",
  },
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Generate and decode QR codes",
    href: "/tools/qr-generator",
    icon: QrCode,
    category: "Generators",
  },
  {
    id: "text-diff",
    name: "Text Diff/Compare",
    description: "Compare two texts and see differences",
    href: "/tools/text-diff",
    icon: FileDiff,
    category: "Testers",
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and validate SQL queries",
    href: "/tools/sql-formatter",
    icon: Database,
    category: "Formatters",
  },
  {
    id: "yaml-formatter",
    name: "YAML Formatter",
    description: "Format and validate YAML files",
    href: "/tools/yaml-formatter",
    icon: FileText,
    category: "Formatters",
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Format and validate XML documents",
    href: "/tools/xml-formatter",
    icon: FileCode2,
    category: "Formatters",
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to readable dates",
    href: "/tools/timestamp-converter",
    icon: Calendar,
    category: "Converters",
  },
  {
    id: "string-utilities",
    name: "String Utilities",
    description: "Count characters, words, lines and more",
    href: "/tools/string-utilities",
    icon: Type,
    category: "Utilities",
  },
  {
    id: "html-encoder",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities",
    href: "/tools/html-encoder",
    icon: Code,
    category: "Encoders",
  },
  {
    id: "csv-converter",
    name: "CSV to JSON",
    description: "Convert CSV to JSON and vice versa",
    href: "/tools/csv-converter",
    icon: Layers,
    category: "Converters",
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text",
    href: "/tools/lorem-ipsum",
    icon: AlignLeft,
    category: "Generators",
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 with preview",
    href: "/tools/image-to-base64",
    icon: Image,
    category: "Converters",
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    description: "Editor with live preview",
    href: "/tools/markdown-editor",
    icon: FileText,
    category: "Formatters",
  },
  {
    id: "json-path",
    name: "JSON Path Tester",
    description: "Test JSONPath expressions on JSON data",
    href: "/tools/json-path",
    icon: FileJson,
    category: "Testers",
  },
  {
    id: "stats",
    name: "Usage Statistics",
    description: "View your tool usage statistics",
    href: "/tools/stats",
    icon: BarChart3,
    category: "Utilities",
  },
  {
    id: "js-minifier",
    name: "JavaScript Minifier",
    description: "Minify and beautify JavaScript code",
    href: "/tools/js-minifier",
    icon: FileCode,
    category: "Formatters",
  },
  {
    id: "html-formatter",
    name: "HTML Formatter",
    description: "Format, validate and minify HTML",
    href: "/tools/html-formatter",
    icon: FileCode2,
    category: "Formatters",
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between different cases",
    href: "/tools/case-converter",
    icon: Type,
    category: "Text Tools",
  },
  {
    id: "curl-generator",
    name: "cURL Generator",
    description: "Generate cURL commands from API requests",
    href: "/tools/curl-generator",
    icon: Terminal,
    category: "Testers",
  },
  {
    id: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Convert JSON to TypeScript interfaces",
    href: "/tools/json-to-typescript",
    icon: FileJson,
    category: "Converters",
  },
  {
    id: "workflow-automation",
    name: "Workflow Automation",
    description: "Create and execute multi-step workflows",
    href: "/tools/workflow-automation",
    icon: Sparkles,
    category: "Utilities",
  },
  {
    id: "graphql-tools",
    name: "GraphQL Tools",
    description: "Build, validate, and format GraphQL queries",
    href: "/tools/graphql-tools",
    icon: Network,
    category: "Testers",
  },
];

export const categories = [
  "Formatters",
  "Encoders",
  "Testers",
  "Security",
  "Generators",
  "Shell Tools",
  "Converters",
  "Utilities",
  "Text Tools",
];

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

